[package]
name = "under-control-ler"
version = "0.1.0"
edition = "2021"

[dependencies]
gilrs = {version="0.10.9", features=["serde-serialize"]}
serde = {version="1.0.210", features=["derive"]}
serde_json = "1.0.128"
