[package]
name = "under-control-ler"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12.2"
gilrs = { version = "0.10.9", default-features=false, features = ["serde-serialize", "xinput"] }
serde = {version="1.0.210", features=["derive"]}
serde_json = "1.0.128"
